# Generated by Django 5.2.10 on 2026-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_quizattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="total",
            field=models.IntegerField(),
        ),
    ]
